- hosts: Compute
  tasks:
    - name: get offline repository from {{repo_file_url}}
      get_url:
        url="{{repo_file_url}}"
        dest="/etc/yum.repos.d/00-ooo.repo"

    - name: clean yum
      command: bash -c "yum clean all"

    - name: get pkgs
      get_url:
        url="http://{{nsx_manager_vip}}:8080/repository/2.4.0.0.0.12456646/HostComponents/rhel76_x86_64/nsx-lcp-2.4.0.0.0.12454259-rhel76_x86_64.tar.gz"
        dest="/root/vmware.tar.gz"

    - name: Create vmware folder
      file:
        path: /root/vmware
        state: directory
    - name: Extract pkgs
      unarchive:
        src="/root/vmware.tar.gz"
        dest="/root"
        copy=node

    - name: reset bond0 TYPE
      command: bash -c "sed -i '/TYPE=OVSPort/d' /etc/sysconfig/network-scripts/ifcfg-bond0"

    - name: reset bond0 DEVICETYPE
      command: bash -c "sed -i '/DEVICETYPE=ovs/d' /etc/sysconfig/network-scripts/ifcfg-bond0"

    - name: reset bond0 OVS_BRIDGE=nsx-switch.0
      command: bash -c "sed -i '/OVS_BRIDGE=nsx-switch.0/d' /etc/sysconfig/network-scripts/ifcfg-bond0"

    - name: restart bond0
      command: bash -c "ifdown bond0 && ifup bond0"

    - name: remove old nsx-switch.0 bridge network config
      command: bash -c "ifdown nsx-switch.0 && rm /etc/sysconfig/network-scripts/ifcfg-nsx-switch.0"

    - name: remove old nsx-managed bridge network config
      command: bash -c "ifdown nsx-managed && rm /etc/sysconfig/network-scripts/ifcfg-nsx-managed"

    - name: remove ovs
      yum:
       name: openvswitch
       state: absent

    - name: install vmware pkgs
      command: bash -c "yum install -y /root/nsx-lcp-rhel76_x86_64/*.rpm"

    - name: reload kernel
      command: bash -c "/etc/init.d/openvswitch force-reload-kmod"
    # thumbprint_manager_ip: 172.21.0.81
    # username: admin
    # password: P@ssw0rd@888
    # thumbprint: 58e8ade2c8791177d85a297111bd74a0118f8811276a8bd13b39a3cdfc0242f5
    - name: Join NSX host
      command: nsxcli -c join management-plane "{{thumbprint_manager_ip}}" username "{{nsx_username}}" password "{{nsx_password}}" thumbprint "{{nsx_thumbprint}}"
